on: [pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v -race ./...
